/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char91indexChar93RouteImport } from './routes/[index]'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as RequirementsRouteImport } from './routes/requirements'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CuisinesRouteImport } from './routes/cuisines'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as AdminFeedbackRouteImport } from './routes/admin.feedback'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const Char91indexChar93Route = Char91indexChar93RouteImport.update({
  id: '/index',
  path: '/index',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const RequirementsRoute = RequirementsRouteImport.update({
  id: '/requirements',
  path: '/requirements',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CuisinesRoute = CuisinesRouteImport.update({
  id: '/cuisines',
  path: '/cuisines',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFeedbackRoute = AdminFeedbackRouteImport.update({
  id: '/admin/feedback',
  path: '/admin/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cuisines': typeof CuisinesRoute
  '/index': typeof Char91indexChar93Route
  '/login': typeof LoginRoute
  '/requirements': typeof RequirementsRoute
  '/results': typeof ResultsRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cuisines': typeof CuisinesRoute
  '/index': typeof Char91indexChar93Route
  '/login': typeof LoginRoute
  '/requirements': typeof RequirementsRoute
  '/results': typeof ResultsRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cuisines': typeof CuisinesRoute
  '/index': typeof Char91indexChar93Route
  '/login': typeof LoginRoute
  '/requirements': typeof RequirementsRoute
  '/results': typeof ResultsRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cuisines'
    | '/index'
    | '/login'
    | '/requirements'
    | '/results'
    | '/admin/feedback'
    | '/api/transcribe'
    | '/.lovable/oauth/consent'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cuisines'
    | '/index'
    | '/login'
    | '/requirements'
    | '/results'
    | '/admin/feedback'
    | '/api/transcribe'
    | '/.lovable/oauth/consent'
  id:
    | '__root__'
    | '/'
    | '/cuisines'
    | '/index'
    | '/login'
    | '/requirements'
    | '/results'
    | '/admin/feedback'
    | '/api/transcribe'
    | '/.lovable/oauth/consent'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CuisinesRoute: typeof CuisinesRoute
  Char91indexChar93Route: typeof Char91indexChar93Route
  LoginRoute: typeof LoginRoute
  RequirementsRoute: typeof RequirementsRoute
  ResultsRoute: typeof ResultsRoute
  AdminFeedbackRoute: typeof AdminFeedbackRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/index': {
      id: '/index'
      path: '/index'
      fullPath: '/index'
      preLoaderRoute: typeof Char91indexChar93RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requirements': {
      id: '/requirements'
      path: '/requirements'
      fullPath: '/requirements'
      preLoaderRoute: typeof RequirementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuisines': {
      id: '/cuisines'
      path: '/cuisines'
      fullPath: '/cuisines'
      preLoaderRoute: typeof CuisinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/feedback': {
      id: '/admin/feedback'
      path: '/admin/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AdminFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CuisinesRoute: CuisinesRoute,
  Char91indexChar93Route: Char91indexChar93Route,
  LoginRoute: LoginRoute,
  RequirementsRoute: RequirementsRoute,
  ResultsRoute: ResultsRoute,
  AdminFeedbackRoute: AdminFeedbackRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
